#!/bin/bash

xpl_path=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

cd ${xpl_path}/..

set -e

if [ ! -d dfp ]
then
	dfp_url="http://packs.download.atmel.com/Atmel.SAMD21_DFP.1.3.395.atpack"
	curl -L $dfp_url --progress-bar -o Atmel.SAMD21_DFP.1.3.395.zip
	
	mkdir dfp
	unzip Atmel.SAMD21_DFP.1.3.395.zip -d dfp
	rm Atmel.SAMD21_DFP.1.3.395.zip

	python3 -m venv env
	source env/bin/activate
	pip install lxml tomlkit
	
	# create arch configurations
	python pkg/pdsc-tools.py dfp/Atmel.SAMD21_DFP.pdsc
	
	# create c++ processors definitions
	find . -name "*.atdf" -exec python pkg/atdf-tools.py {} \;
	
	# cleanup
	rm -rf env
fi